cars = ['bmw','bugati','scania','volvo']
print(f'The car has been sold{cars[0]}')
bugati = 'bugati'
cars.remove(bugati)
print(f"The car has been sold{bugati.upper}")
print(cars)
cars.insert(1,'bugati')
cars.insert(3,'perayd')
print(cars)
cars.append("tara")
print(cars)
cars.pop()
cars.pop()
cars.pop()
cars.pop()
cars.pop()
cars.pop()